version: "3.9"

services:
  db:
    image: "postgres"
    ports:
      - "5432"
    environment:
      POSTGRES_PASSWORD: "eRick22031999"
      POSTGRES_USER: "postgres"
  app:
    build: .
    command: yarn start
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/app
